BEGIN;
UPDATE cards SET session_short_text = 'Quem conduz deve tocar o corpo inteiro da outra pessoa lentamente, sem pressa. A intenção é acordar o corpo.' WHERE id = 'cmq1bcrkp0002uikxxmi4onqw';
UPDATE cards SET session_short_text = 'Quem recebe escolhe três partes do corpo. A outra pessoa conduz usando mãos, boca e respiração.' WHERE id = 'cmq1bcrli0003uikxep36mj4f';
UPDATE cards SET session_short_text = 'Sorteiem um estilo de massagem entre as opções na tela. Quem recebe apenas relaxa e curte.' WHERE id = 'cmq1bcrjz0001uikx166j7wfr';
UPDATE cards SET session_short_text = 'Quem conduz pode beijar, encostar e provocar, mas sem ir direto para o ato principal. O objetivo é manter o desejo crescendo.' WHERE id = 'cmq1bcrmg0004uikx3n5xsohu';
UPDATE cards SET session_short_text = 'Sorteiem quem é o profissional e quem é o cliente. Comecem a massagem sério e deixem o toque ficar íntimo aos poucos.' WHERE id = 'cmq1bcrng0005uikxo341htff';
UPDATE cards SET session_short_text = 'Silêncio total por alguns minutos. Apenas toque, respiração, beijo e olhar. Percebam o corpo um do outro sem fazer perguntas.' WHERE id = 'cmq1bcrop0006uikx2yxhrnu1';
UPDATE cards SET session_short_text = 'Comecem com um beijo na boca, que desce lentamente pelo corpo sem nenhuma pressa.' WHERE id = 'cmq1bcrqw0008uikx6i53qexd';
UPDATE cards SET session_short_text = 'Punição leve para quem pulou cartas nesta sessão. A outra pessoa escolhe uma das quatro provocações na tela.' WHERE id = 'cmq1bcrua000cuikxag0qtnyb';
UPDATE cards SET session_short_text = 'Fiquem com o corpo bem encostado, curtindo a presença um do outro sem pressa para avançar.' WHERE id = 'cmq1bcrt3000buikxl9fhdqna';
UPDATE cards SET session_short_text = 'Diga no ouvido uma frase provocante começando com: "Agora eu queria...". Sem conversa longa.' WHERE id = 'cmq1bcrrr0009uikxtxmk55nm';
UPDATE cards SET session_short_text = 'Quem recebeu a carta escolhe uma das regras na tela para aplicar na próxima rodada. A intenção é provocar sem travar.' WHERE id = 'cmq1bcrsp000auikxdupg952k';
UPDATE cards SET session_short_text = 'Façam uma pausa para tomar um gole e se olhem nos olhos. Quem quiser, diga uma frase curta sobre suas vontades.' WHERE id = 'cmq1bcrpq0007uikxjtgwdtju';
UPDATE cards SET session_short_text = 'A mulher escolhe a ordem dos contatos disponíveis na tela. Ela dita como e quando a cena avança.' WHERE id = 'cmq1bcs2k000kuikx7m0dih8e';
UPDATE cards SET session_short_text = 'A mulher recebe atenção íntima total. Ela tem o direito de guiar o ritmo, a pressão e a posição sem precisar justificar.' WHERE id = 'cmq1bcrv8000duikx18aht153';
UPDATE cards SET session_short_text = 'A mulher escolhe a posição para receber prazer. A outra pessoa apenas obedece ao ritmo dela.' WHERE id = 'cmq1bcrw2000euikxfhpc1wjt';
UPDATE cards SET session_short_text = 'Alternem entre prazer oral intenso e pausas curtas e provocantes para fazer a vontade queimar mais.' WHERE id = 'cmq1bcrxl000fuikxeeiu6r4k';
UPDATE cards SET session_short_text = 'O foco total e exclusivo da cena é dar muito prazer para ela. Sem cobranças por orgasmo, apenas entrega.' WHERE id = 'cmq1bcrzb000huikx4mf2y3s3';
UPDATE cards SET session_short_text = 'A mulher deve guiar o momento usando apenas frases curtas de comando, como "mais devagar" e "continua". A outra pessoa apenas obedece.' WHERE id = 'cmq1bcs0f000iuikxw9vtrxe6';
UPDATE cards SET session_short_text = 'A mulher deve completar a frase: "Hoje eu quero que você...". A outra pessoa obedece aos desejos abertamente confessados.' WHERE id = 'cmq1bcs39000luikx2ak5t8zk';
UPDATE cards SET session_short_text = 'A mulher fica por cima e tem o controle absoluto do ritmo e do corpo. A outra pessoa deve apenas acompanhá-la em submissão.' WHERE id = 'cmq1bcryc000guikxhboo4mk3';
UPDATE cards SET session_short_text = 'A mulher posiciona as mãos da parceira ou parceiro exatamente onde deseja e ninguém pode movê-las sem a ordem dela.' WHERE id = 'cmq1bcs1z000juikx6vo8uv86';
UPDATE cards SET session_short_text = 'Quem está recebendo o prazer escolhe a técnica desejada na tela. Quem conduz foca apenas em obedecer, focar e executar.' WHERE id = 'cmq1bcsai000suikxyf8i20l6';
UPDATE cards SET session_short_text = 'Sem vídeos nesta carta. Quem recebe apenas relaxa. Quem conduz usa mãos e boca, oscilando as sensações.' WHERE id = 'cmq1bcs6h000ouikxwhbojn1n';
UPDATE cards SET session_short_text = 'Quem conduz inicia o prazer, e deve interromper de forma bem safada e provocante cada vez que o pico parecer muito perto.' WHERE id = 'cmq1bcs9y000ruikxzuj0ornm';
UPDATE cards SET session_short_text = 'Sorteiem um vídeo curto na tela. O desafio não é copiar tudo igualzinho, mas sim tentar copiar a mesma energia que passa.' WHERE id = 'cmq1bcs90000quikx19gg9upk';
UPDATE cards SET session_short_text = 'Sorteiem um vídeo com o aplicativo. Quem for receber o prazer, assiste à tela relaxando. Quem for conduzir, executa com vontade.' WHERE id = 'cmq1bcs7r000puikx0nhodx1e';
UPDATE cards SET session_short_text = 'Sorteiem um vídeo picante focado na tela para ela. A mulher assiste à cena enquanto recebe seu prazer da forma que mais a excita.' WHERE id = 'cmq1bcs48000muikxnfbmjn8e';
UPDATE cards SET session_short_text = 'Sorteiem um vídeo mais forte focado no gosto dele. O homem assiste à cena enquanto recebe atenção de quem estiver conduzindo.' WHERE id = 'cmq1bcs59000nuikxwuc29qt5';
UPDATE cards SET session_short_text = 'Vocês têm um desafio rigoroso: estão proibidos de trocar de posição por até três minutos. Variem só beijos, intensidade e atrito.' WHERE id = 'cmq1bcsdc000wuikx90n5ux1t';
UPDATE cards SET session_short_text = 'A regra agora é extrema para explodir a vontade: proibido penetração por alguns minutos. Vale absolutamente tudo o resto para instigar.' WHERE id = 'cmq1bcsex000yuikx2k217q39';
UPDATE cards SET session_short_text = 'Aviso de intensidade alta: tentem fazer algo muito mais forte e selvagem, mas apenas se ambos estiverem completamente prontos.' WHERE id = 'cmq1bcsfq000zuikxop4k3x4w';
UPDATE cards SET session_short_text = 'A mulher é a dona da cena. Ela define a posição inicial e dita o ritmo pesado ou suave com o qual o ato se desenrola.' WHERE id = 'cmq1bcsbm000uuikxmfzpkq6v';
UPDATE cards SET session_short_text = 'Iniciem de forma bem lenta e suave. A cada minuto, façam a intensidade e velocidade escalar mais, até se tornar animal.' WHERE id = 'cmq1bcsb5000tuikx37qwyqu9';
UPDATE cards SET session_short_text = 'A intensidade agora tem tudo pra ficar selvagem, mas quem estiver por cima não pode fechar os olhos pros sinais de prazer da outra.' WHERE id = 'cmq1bcscj000vuikxyv6npxly';
UPDATE cards SET session_short_text = 'A mulher tem a última palavra e pode encerrar ou quebrar a cena escolhendo comanda o final usando as opções exibidas no card.' WHERE id = 'cmq1bcse3000xuikxcczoi95g';
UPDATE cards SET session_short_text = 'Sorteiem na tela uma regra que causará dor ou tensão, e que deverá ser absolutamente inquebrável por toda essa próxima rodada.' WHERE id = 'cmq1bcsj30016uikxrbgoi0zz';
UPDATE cards SET session_short_text = 'A cena continua, mas fechem os olhos e imaginem em silêncio que há um estranho observando e desejando cada detalhe da transa de vocês.' WHERE id = 'cmq1bcsik0015uikx7qjv4aet';
UPDATE cards SET session_short_text = 'Aperte para sortear um fetiche. Incorporem os personagens sem hesitar. Puxem o ar do quarto todo pra deixar a interpretação rolar.' WHERE id = 'cmq1bcsh10010uikx86noco8d';
UPDATE cards SET session_short_text = 'Feche os olhos se quiser, e pense na sua pior fantasia. O combinado da carta é aproveitar no absoluto mistério, ninguém precisa falar quem é.' WHERE id = 'cmq1bcshk0011uikxvc5dwf7k';
UPDATE cards SET session_short_text = 'Quem está lendo as ordens agora deve sussurrar seu fetiche bem baixo e com voz submissa ou de comando. Quem ouvir, executa de volta.' WHERE id = 'cmq1bcshw0012uikxji93i7zm';
UPDATE cards SET session_short_text = 'Interpretem dois estranhos em um hotel que se querem pra caramba, mas não querem admitir. Deixe as palavras levarem aos toques mais lentos.' WHERE id = 'cmq1bcsi50013uikx8k6tgtej';
UPDATE cards SET session_short_text = 'Sejam o cliente inocente e o profissional sujo. O atendimento que começou totalmente protocolar, passa a cruzar os limites.' WHERE id = 'cmq1bcsi80014uikxs83gh7ob';
COMMIT;
