import { PrismaClient, CardCategory, CardIntensity, CardTag, EroticFunction, ProgressionRole, ReceiverRule, SessionStage } from '@prisma/client';
import { Pool } from 'pg';
import { PrismaPg } from '@prisma/adapter-pg';
import { config } from 'dotenv';

config();

let connectionString = process.env.DATABASE_URL || '';

if (connectionString.startsWith('prisma+postgres://localhost')) {
  connectionString = 'postgres://postgres:postgres@localhost:51214/template1?sslmode=disable';
}

const pool = new Pool({ connectionString });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });
﻿const cards = [
  {
    "position": 1,
    "system_key": "deriva-v2-card-001",
    "title": "Mãos lentas",
    "category": "AZUL",
    "intensity": "LEVE",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "TOQUE_LEVE",
    "stage": "OPENING",
    "erotic_function": "PREPARO",
    "progression_role": "ABRIR",
    "body": "Óleo nas mãos e desliza pelo corpo todo dela, bem devagar. Deixa ela arrepiada antes de qualquer coisa.",
    "session_short_text": "Óleo nas mãos, desliza pelo corpo devagar. Deixa ela arrepiada.",
    "random_options_enabled": false,
    "persist_random_option": true,
  },
  {
    "position": 2,
    "system_key": "deriva-v2-card-002",
    "title": "Massagem que esquenta",
    "category": "AZUL",
    "intensity": "LEVE",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "TOQUE_LEVE",
    "stage": "OPENING",
    "erotic_function": "PREPARO",
    "progression_role": "ABRIR",
    "body": "Massageia as costas dela e vai descendo pras coxas e pra bunda, cada vez mais safado. Deixa ela te puxando pedindo mais.",
    "session_short_text": "Massageia as costas descendo. Deixa ela pedindo mais.",
    "random_options_enabled": false,
    "persist_random_option": true,
  },
  {
    "position": 3,
    "system_key": "deriva-v2-card-003",
    "title": "Despe devagar",
    "category": "AZUL",
    "intensity": "LEVE",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "TOQUE_LEVE",
    "stage": "OPENING",
    "erotic_function": "PREPARO",
    "progression_role": "ABRIR",
    "body": "Tira a roupa dela peça por peça, beijando cada parte que aparece. Sem pressa nenhuma.",
    "session_short_text": "Tira peça por peça, beijando cada parte. Sem pressa.",
    "random_options_enabled": false,
    "persist_random_option": true,
  },
  {
    "position": 4,
    "system_key": "deriva-v2-card-004",
    "title": "Beijo no pescoço",
    "category": "AZUL",
    "intensity": "LEVE",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "TOQUE_LEVE",
    "stage": "OPENING",
    "erotic_function": "PREPARO",
    "progression_role": "ABRIR",
    "body": "Afasta o cabelo dela e beija o pescoço bem devagar, coladinho por trás. Sente ela arrepiar inteira.",
    "session_short_text": "Beija o pescoço dela bem devagar. Sente arrepiação.",
    "random_options_enabled": false,
    "persist_random_option": true,
  },
  {
    "position": 5,
    "system_key": "deriva-v2-card-005",
    "title": "Mão por baixo da roupa",
    "category": "AZUL",
    "intensity": "LEVE",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "TOQUE_LEVE",
    "stage": "OPENING",
    "erotic_function": "PREPARO",
    "progression_role": "ABRIR",
    "body": "Ainda vestida, passa a mão por baixo e provoca onde der. Deixa ela louca pra arrancar tudo.",
    "session_short_text": "Passa mão por baixo. Deixa ela louca pra arrancar tudo.",
    "random_options_enabled": false,
    "persist_random_option": true,
  },
  {
    "position": 6,
    "system_key": "deriva-v2-card-006",
    "title": "Sopro quente",
    "category": "AZUL",
    "intensity": "LEVE",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "TOQUE_LEVE",
    "stage": "OPENING",
    "erotic_function": "PREPARO",
    "progression_role": "ABRIR",
    "body": "Passa a língua e sopra na pele dela, do pescoço até a barriga. Faz ela se contorcer.",
    "session_short_text": "Sopra na pele, do pescoço até barriga. Faz contorcer.",
    "random_options_enabled": false,
    "persist_random_option": true,
  },
  {
    "position": 7,
    "system_key": "deriva-v2-card-007",
    "title": "Provocação vestida",
    "category": "AZUL",
    "intensity": "LEVE",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "TOQUE_LEVE",
    "stage": "OPENING",
    "erotic_function": "PREPARO",
    "progression_role": "ABRIR",
    "body": "Dança coladinho nela ainda vestido, esfregando o corpo. Deixa os dois doidos antes de começar.",
    "session_short_text": "Dança coladinho vestido. Deixa os dois doidos.",
    "random_options_enabled": false,
    "persist_random_option": true,
  },
  {
    "position": 8,
    "system_key": "deriva-v2-card-008",
    "title": "Mordidas leves",
    "category": "AZUL",
    "intensity": "LEVE",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "TOQUE_LEVE",
    "stage": "OPENING",
    "erotic_function": "PREPARO",
    "progression_role": "ABRIR",
    "body": "Morde de leve a orelha, o pescoço e o ombro dela. Quero ela pedindo mais.",
    "session_short_text": "Morde orelha, pescoço e ombro. Deixa pedindo mais.",
    "random_options_enabled": false,
    "persist_random_option": true,
  },
  {
    "position": 9,
    "system_key": "deriva-v2-card-009",
    "title": "Beijo que desce",
    "category": "DERIVA",
    "intensity": "QUENTE",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "PROVOCACAO",
    "stage": "WARMUP",
    "erotic_function": "PREPARO",
    "progression_role": "ABRIR",
    "body": "Desce beijando o corpo dela até as coxas, provocando. Faz ela implorar pra você chegar onde ela quer.",
    "session_short_text": "Desce beijando. Faz ela implorar.",
    "random_options_enabled": false,
    "persist_random_option": true,
  },
  {
    "position": 10,
    "system_key": "deriva-v2-card-010",
    "title": "Pausa grudada",
    "category": "DERIVA",
    "intensity": "QUENTE",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "PROVOCACAO",
    "stage": "WARMUP",
    "erotic_function": "PREPARO",
    "progression_role": "ABRIR",
    "body": "Para tudo e cola o corpo no dela, respirando junto, sem pressa. Curte o calor antes de continuar.",
    "session_short_text": "Para e cola o corpo. Respira junto sem pressa.",
    "random_options_enabled": false,
    "persist_random_option": true,
  },
  {
    "position": 11,
    "system_key": "deriva-v2-card-011",
    "title": "Olhos nos olhos",
    "category": "DERIVA",
    "intensity": "QUENTE",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "PROVOCACAO",
    "stage": "WARMUP",
    "erotic_function": "PREPARO",
    "progression_role": "ABRIR",
    "body": "Beija ela bem fundo, sem pressa, olhando no olho. Deixa o tesão crescer no beijo.",
    "session_short_text": "Beija fundo olhando no olho. Tesão cresce no beijo.",
    "random_options_enabled": false,
    "persist_random_option": true,
  },
  {
    "position": 12,
    "system_key": "deriva-v2-card-012",
    "title": "Respira junto",
    "category": "DERIVA",
    "intensity": "QUENTE",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "PROVOCACAO",
    "stage": "WARMUP",
    "erotic_function": "PREPARO",
    "progression_role": "ABRIR",
    "body": "Encosta a testa na dela e respira no mesmo ritmo, com as mãos passeando pelo corpo. Sente os dois acelerarem.",
    "session_short_text": "Encosta testa e respira junto. Mãos passeiam.",
    "random_options_enabled": false,
    "persist_random_option": true,
  },
  {
    "position": 13,
    "system_key": "deriva-v2-card-013",
    "title": "Conta no ouvido",
    "category": "DERIVA",
    "intensity": "QUENTE",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "PROVOCACAO",
    "stage": "WARMUP",
    "erotic_function": "PREPARO",
    "progression_role": "ABRIR",
    "body": "Cola no ouvido dela e conta baixinho o que você tá doido pra fazer. Deixa ela molhada só de ouvir.",
    "session_short_text": "Cola no ouvido e conta. Deixa molhada.",
    "random_options_enabled": false,
    "persist_random_option": true,
  },
  {
    "position": 14,
    "system_key": "deriva-v2-card-014",
    "title": "Provoca e foge",
    "category": "DERIVA",
    "intensity": "QUENTE",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "PROVOCACAO",
    "stage": "WARMUP",
    "erotic_function": "PREPARO",
    "progression_role": "ABRIR",
    "body": "Beija e toca quase onde ela quer, e afasta na hora. Repete até ela te puxar com força.",
    "session_short_text": "Beija, toca e afasta. Repete até ela puxar.",
    "random_options_enabled": false,
    "persist_random_option": true,
  },
  {
    "position": 15,
    "system_key": "deriva-v2-card-015",
    "title": "Ela guia",
    "category": "ROSA",
    "intensity": "INTENSO",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "MAOS_NELA",
    "stage": "TEASING",
    "erotic_function": "PRAZER_NELA",
    "progression_role": "AQUECER",
    "body": "Faz oral nela e deixa ela guiar a sua cabeça, o ritmo e a pressão. Foco total nela.",
    "session_short_text": "Faz oral e deixa ela guiar. Foco total.",
    "random_options_enabled": false,
    "persist_random_option": true,
  },
  {
    "position": 16,
    "system_key": "deriva-v2-card-016",
    "title": "Oral sem pressa",
    "category": "ROSA",
    "intensity": "INTENSO",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "MAOS_NELA",
    "stage": "TEASING",
    "erotic_function": "PRAZER_NELA",
    "progression_role": "AQUECER",
    "body": "Faz oral nela sem pressa, língua e dedos juntos, sem penetração. Tomara que ela goze na sua boca.",
    "session_short_text": "Oral sem pressa, língua e dedos. Gozo na boca.",
    "random_options_enabled": false,
    "persist_random_option": true,
  },
  {
    "position": 17,
    "system_key": "deriva-v2-card-017",
    "title": "Boca e pausa",
    "category": "ROSA",
    "intensity": "INTENSO",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "MAOS_NELA",
    "stage": "TEASING",
    "erotic_function": "PRAZER_NELA",
    "progression_role": "AQUECER",
    "body": "Chupa ela gostoso e para bem na hora que ela tá quase. Deixa ela implorando entre uma e outra.",
    "session_short_text": "Chupa e para na hora. Deixa implorando.",
    "random_options_enabled": false,
    "persist_random_option": true,
  },
  {
    "position": 18,
    "system_key": "deriva-v2-card-018",
    "title": "Dedos e boca",
    "category": "ROSA",
    "intensity": "INTENSO",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "MAOS_NELA",
    "stage": "TEASING",
    "erotic_function": "PRAZER_NELA",
    "progression_role": "AQUECER",
    "body": "Junta os dedos com a boca e acha o ponto que faz ela arquear. Não sai de lá.",
    "session_short_text": "Dedos com boca. Acha ponto que faz arquear.",
    "random_options_enabled": false,
    "persist_random_option": true,
  },
  {
    "position": 19,
    "system_key": "deriva-v2-card-019",
    "title": "Mãos nele",
    "category": "ROSA",
    "intensity": "INTENSO",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "MAOS_NELA",
    "stage": "TEASING",
    "erotic_function": "PRAZER_NELA",
    "progression_role": "AQUECER",
    "body": "Pega ele firme, do jeito que ele gosta, começa devagar e vai apertando o ritmo. Deixa ele duro feito pedra.",
    "session_short_text": "Pega firme, começa devagar, aperta ritmo.",
    "random_options_enabled": false,
    "persist_random_option": true,
  },
  {
    "position": 20,
    "system_key": "deriva-v2-card-020",
    "title": "Boca nele",
    "category": "ROSA",
    "intensity": "INTENSO",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "MAOS_NELA",
    "stage": "TEASING",
    "erotic_function": "PRAZER_NELA",
    "progression_role": "AQUECER",
    "body": "Faz oral nele caprichando, sem deixar gozar. Para na hora que ele chegar perto e deixa ele louco.",
    "session_short_text": "Faz oral caprichando. Para no limite.",
    "random_options_enabled": false,
    "persist_random_option": true,
  },
  {
    "position": 21,
    "system_key": "deriva-v2-card-021",
    "title": "Sessenta e nove",
    "category": "ROSA",
    "intensity": "INTENSO",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "MAOS_NELA",
    "stage": "TEASING",
    "erotic_function": "PRAZER_NELA",
    "progression_role": "AQUECER",
    "body": "Façam 69, oral um no outro ao mesmo tempo, sem ninguém gozar ainda.",
    "session_short_text": "69 ao mesmo tempo, sem gozar ainda.",
    "random_options_enabled": false,
    "persist_random_option": true,
  },
  {
    "position": 22,
    "system_key": "deriva-v2-card-022",
    "title": "Vibrador nela",
    "category": "ROSA",
    "intensity": "INTENSO",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "MAOS_NELA",
    "stage": "TEASING",
    "erotic_function": "PRAZER_NELA",
    "progression_role": "AQUECER",
    "body": "Liga o vibrador nela enquanto beija o corpo dela. Sobe a intensidade no tempo dela.",
    "session_short_text": "Liga vibrador enquanto beija. Sobe intensidade.",
    "random_options_enabled": false,
    "persist_random_option": true,
  },
  {
    "position": 23,
    "system_key": "deriva-v2-card-023",
    "title": "Por cima da calcinha",
    "category": "ROSA",
    "intensity": "INTENSO",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "MAOS_NELA",
    "stage": "TEASING",
    "erotic_function": "PRAZER_NELA",
    "progression_role": "AQUECER",
    "body": "Lambe e aperta por cima da calcinha dela primeiro, sem tirar. Faz ela pedir pra você arrancar.",
    "session_short_text": "Por cima da calcinha. Faz pedir pra arrancar.",
    "random_options_enabled": false,
    "persist_random_option": true,
  },
  {
    "position": 24,
    "system_key": "deriva-v2-card-024",
    "title": "Quase dentro",
    "category": "ROSA",
    "intensity": "INTENSO",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "MAOS_NELA",
    "stage": "TEASING",
    "erotic_function": "PRAZER_NELA",
    "progression_role": "AQUECER",
    "body": "Encosta nela e provoca só na entrada, sem entrar de verdade. Deixa ela louca pra você ir fundo.",
    "session_short_text": "Provoca só na entrada. Deixa louca.",
    "random_options_enabled": false,
    "persist_random_option": true,
  },
  {
    "position": 25,
    "system_key": "deriva-v2-card-025",
    "title": "Sentada na sua boca",
    "category": "ROSA",
    "intensity": "INTENSO",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "MAOS_NELA",
    "stage": "TEASING",
    "erotic_function": "PRAZER_NELA",
    "progression_role": "AQUECER",
    "body": "Deita e deixa ela sentar na sua boca, do jeito que ela quiser. Que ela use você como bem entender.",
    "session_short_text": "Deixa sentar na boca. Ela usa como quiser.",
    "random_options_enabled": false,
    "persist_random_option": true,
  },
  {
    "position": 26,
    "system_key": "deriva-v2-card-026",
    "title": "Mãos presas",
    "category": "ROSA",
    "intensity": "INTENSO",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "MAOS_NELA",
    "stage": "TEASING",
    "erotic_function": "PRAZER_NELA",
    "progression_role": "AQUECER",
    "body": "Prende as mãos dela de leve e dá prazer com calma, sem deixar ela reagir. Deixa ela toda à sua mercê.",
    "session_short_text": "Prende mãos, dá prazer. Ela à sua mercê.",
    "random_options_enabled": false,
    "persist_random_option": true,
  },
  {
    "position": 27,
    "system_key": "deriva-v2-card-027",
    "title": "Tela para ela",
    "category": "ROXO",
    "intensity": "INTENSO",
    "is_invertible": false,
    "requires_video": true,
    "receiver_rule": "NONE",
    "primary_tag": "VIDEO",
    "stage": "BUILDUP",
    "erotic_function": "PRAZER_NELA",
    "progression_role": "PROVOCAR",
    "body": "Com o vídeo dela rolando, não para de dar prazer nela com boca e dedos. Repara no que faz ela arquear.",
    "session_short_text": "Vídeo rolando. Prazer com boca e dedos.",
    "random_options_enabled": false,
    "persist_random_option": true,
  },
  {
    "position": 28,
    "system_key": "deriva-v2-card-028",
    "title": "Tela para ele",
    "category": "ROXO",
    "intensity": "INTENSO",
    "is_invertible": false,
    "requires_video": true,
    "receiver_rule": "NONE",
    "primary_tag": "VIDEO",
    "stage": "BUILDUP",
    "erotic_function": "PRAZER_NELA",
    "progression_role": "PROVOCAR",
    "body": "Com o vídeo dele rolando, capricha na boca e nas mãos nele, sem deixar ele gozar.",
    "session_short_text": "Vídeo dele. Capricha na boca e mãos.",
    "random_options_enabled": false,
    "persist_random_option": true,
  },
  {
    "position": 29,
    "system_key": "deriva-v2-card-029",
    "title": "Os dois assistindo",
    "category": "ROXO",
    "intensity": "INTENSO",
    "is_invertible": false,
    "requires_video": true,
    "receiver_rule": "NONE",
    "primary_tag": "VIDEO",
    "stage": "BUILDUP",
    "erotic_function": "PRAZER_NELA",
    "progression_role": "PROVOCAR",
    "body": "Deixa o vídeo rolando e se tocam juntos, olhando a cena e um pro outro. Sobe o clima sem pressa.",
    "session_short_text": "Vídeo rolando, se tocam juntos.",
    "random_options_enabled": false,
    "persist_random_option": true,
  },
  {
    "position": 30,
    "system_key": "deriva-v2-card-030",
    "title": "Imita o vídeo",
    "category": "ROXO",
    "intensity": "INTENSO",
    "is_invertible": false,
    "requires_video": true,
    "receiver_rule": "NONE",
    "primary_tag": "VIDEO",
    "stage": "BUILDUP",
    "erotic_function": "PRAZER_NELA",
    "progression_role": "PROVOCAR",
    "body": "Escolhe um momento do vídeo e faz igualzinho nela. Deixa ela surpresa com o que vem.",
    "session_short_text": "Imita momento do vídeo. Deixa surpresa.",
    "random_options_enabled": false,
    "persist_random_option": true,
  },
  {
    "position": 31,
    "system_key": "deriva-v2-card-031",
    "title": "Vídeo e penetração",
    "category": "ROXO",
    "intensity": "INTENSO",
    "is_invertible": false,
    "requires_video": true,
    "receiver_rule": "NONE",
    "primary_tag": "VIDEO",
    "stage": "BUILDUP",
    "erotic_function": "PRAZER_NELA",
    "progression_role": "PROVOCAR",
    "body": "Com o vídeo rolando, entra nela devagar enquanto ela assiste. Deixa ela curtir os dois ao mesmo tempo.",
    "session_short_text": "Vídeo rolando, entra devagar.",
    "random_options_enabled": false,
    "persist_random_option": true,
  },
  {
    "position": 32,
    "system_key": "deriva-v2-card-032",
    "title": "Narra o vídeo",
    "category": "ROXO",
    "intensity": "INTENSO",
    "is_invertible": false,
    "requires_video": true,
    "receiver_rule": "NONE",
    "primary_tag": "VIDEO",
    "stage": "BUILDUP",
    "erotic_function": "PRAZER_NELA",
    "progression_role": "PROVOCAR",
    "body": "Cola no ouvido dela e descreve o que tá rolando na tela, bem safado. Deixa ela mais excitada que a própria cena.",
    "session_short_text": "Narra o vídeo no ouvido dela.",
    "random_options_enabled": false,
    "persist_random_option": true,
  },
  {
    "position": 33,
    "system_key": "deriva-v2-card-033",
    "title": "Ela por cima",
    "category": "VERMELHO",
    "intensity": "INTENSO",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "PENETRACAO",
    "stage": "INTENSE",
    "erotic_function": "PRAZER_NELA",
    "progression_role": "INTENSIFICAR",
    "body": "Senta nele e domina o ritmo, no seu tempo. Que ele aguente sem gozar.",
    "session_short_text": "Senta e domina o ritmo. Ele aguenta.",
    "random_options_enabled": false,
    "persist_random_option": true,
  },
  {
    "position": 34,
    "system_key": "deriva-v2-card-034",
    "title": "Posição escolhida por ela",
    "category": "VERMELHO",
    "intensity": "INTENSO",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "PENETRACAO",
    "stage": "INTENSE",
    "erotic_function": "PRAZER_NELA",
    "progression_role": "INTENSIFICAR",
    "body": "Escolhe a posição que te faz gozar mais e manda nele. Hoje o seu corpo é quem manda.",
    "session_short_text": "Escolhe posição, manda nele.",
    "random_options_enabled": false,
    "persist_random_option": true,
  },
  {
    "position": 35,
    "system_key": "deriva-v2-card-035",
    "title": "Ritmo crescente",
    "category": "VERMELHO",
    "intensity": "INTENSO",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "PENETRACAO",
    "stage": "INTENSE",
    "erotic_function": "PRAZER_NELA",
    "progression_role": "INTENSIFICAR",
    "body": "Entra fundo e vai do devagar ao fogo, sem deixar ninguém gozar ainda.",
    "session_short_text": "Vai do devagar ao fogo sem gozar.",
    "random_options_enabled": false,
    "persist_random_option": true,
  },
  {
    "position": 36,
    "system_key": "deriva-v2-card-036",
    "title": "De quatro",
    "category": "VERMELHO",
    "intensity": "INTENSO",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "PENETRACAO",
    "stage": "INTENSE",
    "erotic_function": "PRAZER_NELA",
    "progression_role": "INTENSIFICAR",
    "body": "Põe ela de quatro e vai fundo, com a mão nas costas e no cabelo dela. No ritmo que ela pedir.",
    "session_short_text": "De quatro, mão nas costas e cabelo.",
    "random_options_enabled": false,
    "persist_random_option": true,
  },
  {
    "position": 37,
    "system_key": "deriva-v2-card-037",
    "title": "Pernas pra cima",
    "category": "VERMELHO",
    "intensity": "INTENSO",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "PENETRACAO",
    "stage": "INTENSE",
    "erotic_function": "PRAZER_NELA",
    "progression_role": "INTENSIFICAR",
    "body": "Deita ela e joga as pernas dela pro seu ombro, indo bem fundo. Sente ela apertando você.",
    "session_short_text": "Pernas pro ombro, fundo.",
    "random_options_enabled": false,
    "persist_random_option": true,
  },
  {
    "position": 38,
    "system_key": "deriva-v2-card-038",
    "title": "Conchinha",
    "category": "VERMELHO",
    "intensity": "INTENSO",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "PENETRACAO",
    "stage": "INTENSE",
    "erotic_function": "PRAZER_NELA",
    "progression_role": "INTENSIFICAR",
    "body": "Entra nela de ladinho, coladinho, beijando o pescoço e com a mão na frente dela. Devagar e fundo.",
    "session_short_text": "Conchinha, beijando pescoço.",
    "random_options_enabled": false,
    "persist_random_option": true,
  },
  {
    "position": 39,
    "system_key": "deriva-v2-card-039",
    "title": "Contra a parede",
    "category": "VERMELHO",
    "intensity": "INTENSO",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "PENETRACAO",
    "stage": "INTENSE",
    "erotic_function": "PRAZER_NELA",
    "progression_role": "INTENSIFICAR",
    "body": "Prensa ela na parede e entra com vontade, segurando ela no colo. Deixa ela sem chão.",
    "session_short_text": "Na parede, segura no colo.",
    "random_options_enabled": false,
    "persist_random_option": true,
  },
  {
    "position": 40,
    "system_key": "deriva-v2-card-040",
    "title": "Troca quem manda",
    "category": "VERMELHO",
    "intensity": "INTENSO",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "PENETRACAO",
    "stage": "INTENSE",
    "erotic_function": "PRAZER_NELA",
    "progression_role": "INTENSIFICAR",
    "body": "Toma o ritmo na mão e dita tudo até ela implorar. Depois devolve o comando pra ela.",
    "session_short_text": "Você comanda, depois ela.",
    "random_options_enabled": false,
    "persist_random_option": true,
  },
  {
    "position": 41,
    "system_key": "deriva-v2-card-041",
    "title": "Quase gozando",
    "category": "VERMELHO",
    "intensity": "INTENSO",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "PENETRACAO",
    "stage": "INTENSE",
    "erotic_function": "PRAZER_NELA",
    "progression_role": "INTENSIFICAR",
    "body": "Vai até a beira e PARA. Segura os dois ali no limite o quanto der.",
    "session_short_text": "Vai à beira e PARA no limite.",
    "random_options_enabled": false,
    "persist_random_option": true,
  },
  {
    "position": 42,
    "system_key": "deriva-v2-card-042",
    "title": "Fundo e devagar",
    "category": "VERMELHO",
    "intensity": "INTENSO",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "PENETRACAO",
    "stage": "INTENSE",
    "erotic_function": "PRAZER_NELA",
    "progression_role": "INTENSIFICAR",
    "body": "Diminui tudo e vai o mais fundo que der, sentindo cada centímetro. Deixa ela louca com a lentidão.",
    "session_short_text": "Fundo e devagar, sente cada centímetro.",
    "random_options_enabled": false,
    "persist_random_option": true,
  },
  {
    "position": 43,
    "system_key": "deriva-v2-card-043",
    "title": "Sem soltar a boca",
    "category": "VERMELHO",
    "intensity": "INTENSO",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "PENETRACAO",
    "stage": "INTENSE",
    "erotic_function": "PRAZER_NELA",
    "progression_role": "INTENSIFICAR",
    "body": "Entra nela sem largar o beijo, se mexendo enquanto beija. Fogo e conexão ao mesmo tempo.",
    "session_short_text": "Sem largar beijo. Fogo e conexão.",
    "random_options_enabled": false,
    "persist_random_option": true,
  },
  {
    "position": 44,
    "system_key": "deriva-v2-card-044",
    "title": "Olha ela gozar",
    "category": "VERMELHO",
    "intensity": "INTENSO",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "PENETRACAO",
    "stage": "INTENSE",
    "erotic_function": "PRAZER_NELA",
    "progression_role": "INTENSIFICAR",
    "body": "Mantém certinho o ritmo que leva ela ao limite e não muda nada. Olha no olho dela enquanto ela goza.",
    "session_short_text": "Mantém ritmo, olha no olho.",
    "random_options_enabled": false,
    "persist_random_option": true,
  },
  {
    "position": 45,
    "system_key": "deriva-v2-card-045",
    "title": "Ordem sussurrada",
    "category": "PRETO",
    "intensity": "PICO",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "DOMINACAO",
    "stage": "PEAK",
    "erotic_function": "PRAZER_NELA",
    "progression_role": "PICO",
    "body": "Sussurra no ouvido dele o que você quer, bem safada. Ele cumpre e vão juntos.",
    "session_short_text": "Sussurra ordem no ouvido dele.",
    "random_options_enabled": false,
    "persist_random_option": true,
  },
  {
    "position": 46,
    "system_key": "deriva-v2-card-046",
    "title": "Ela no comando do fim",
    "category": "PRETO",
    "intensity": "PICO",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "DOMINACAO",
    "stage": "PEAK",
    "erotic_function": "PRAZER_NELA",
    "progression_role": "PICO",
    "body": "Decide o final e manda nele. Quando os dois tiverem quase, vão juntos.",
    "session_short_text": "Ela decide o final, manda.",
    "random_options_enabled": false,
    "persist_random_option": true,
  },
  {
    "position": 47,
    "system_key": "deriva-v2-card-047",
    "title": "Explosão juntos",
    "category": "PRETO",
    "intensity": "PICO",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "DOMINACAO",
    "stage": "PEAK",
    "erotic_function": "PRAZER_NELA",
    "progression_role": "PICO",
    "body": "Sem segurar mais nada, vai fundo até os dois gozarem ao mesmo tempo.",
    "session_short_text": "Vai fundo, gozam juntos.",
    "random_options_enabled": false,
    "persist_random_option": true,
  },
  {
    "position": 48,
    "system_key": "deriva-v2-card-048",
    "title": "Goza onde ela manda",
    "category": "PRETO",
    "intensity": "PICO",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "DOMINACAO",
    "stage": "PEAK",
    "erotic_function": "PRAZER_NELA",
    "progression_role": "PICO",
    "body": "Pergunta pra ela onde ela quer e obedece na hora. Deixa ela decidir o seu fim.",
    "session_short_text": "Pergunta onde, obedece na hora.",
    "random_options_enabled": false,
    "persist_random_option": true,
  },
  {
    "position": 49,
    "system_key": "deriva-v2-card-049",
    "title": "Diz o que sente",
    "category": "PRETO",
    "intensity": "PICO",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "DOMINACAO",
    "stage": "PEAK",
    "erotic_function": "PRAZER_NELA",
    "progression_role": "PICO",
    "body": "Fala alto e safado tudo que tá sentindo enquanto vai com tudo. Deixa ela mais louca com a sua voz.",
    "session_short_text": "Fala tudo que sente, voz safada.",
    "random_options_enabled": false,
    "persist_random_option": true,
  },
  {
    "position": 50,
    "system_key": "deriva-v2-card-050",
    "title": "Rendição total",
    "category": "PRETO",
    "intensity": "PICO",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "DOMINACAO",
    "stage": "PEAK",
    "erotic_function": "PRAZER_NELA",
    "progression_role": "PICO",
    "body": "Faz tudo que ela pedir, sem questionar, até o último segundo. Hoje você é dela.",
    "session_short_text": "Faz tudo que ela pedir. Você é dela.",
    "random_options_enabled": false,
    "persist_random_option": true,
  }
];



const randomOptionsBySystemKey: Record<string, Array<{ label: string; instruction_short: string; instruction_full: string; weight?: number }>> = {
  "deriva-v1-card-001": [
    {
      label: "Massagem livre",
      instruction_short: "Faz uma massagem gostosa no corpo inteiro. Ela relaxa e curte.",
      instruction_full: "Faz uma massagem gostosa no corpo inteiro. Ela relaxa e guia o ritmo com pouco som e pouca palavra.",
    },
    {
      label: "Profissional e cliente",
      instruction_short: "Começa como profissional e cliente.",
      instruction_full: "Entra na cena de profissional e cliente. Começa técnico, sério e atento, deixando o toque ficar íntimo aos poucos.",
    },
    {
      label: "Deslize provocante",
      instruction_short: "Deixa a massagem profissional escorregar pro íntimo.",
      instruction_full: "Começa como massagem profissional e deixa pequenos deslizes provocantes aparecerem devagar, sempre percebendo a reação dela.",
    },
  ],
  "deriva-v1-card-012": [
    {
      label: "Beijo demorado",
      instruction_short: "Dá um beijo demorado e cheio de intenção.",
      instruction_full: "Dá um beijo demorado, aproxima o corpo e deixa a provocação crescer sem pressa.",
    },
    {
      label: "Toque por cima da roupa",
      instruction_short: "Provoca por cima da roupa.",
      instruction_full: "Toca por cima da roupa com calma, pressão e malícia, sem entregar tudo de uma vez.",
    },
    {
      label: "Frase safada no ouvido",
      instruction_short: "Sussurra uma frase safada no ouvido.",
      instruction_full: "Chega no ouvido e solta uma frase safada, curta e direta, do jeito que deixa o clima mais perigoso.",
    },
    {
      label: "Sem tocar",
      instruction_short: "Fica sem tocar por um instante e só olha.",
      instruction_full: "Fica sem tocar por um instante. Só olha, respira perto e deixa a vontade incomodar gostoso.",
    },
  ],
  "deriva-v1-card-036": [
    {
      label: "Massagista e cliente",
      instruction_short: "Entra na cena de massagista e cliente.",
      instruction_full: "Entra na cena de massagista e cliente. Começa formal e deixa o desejo aparecer no toque.",
    },
    {
      label: "Profissional de saúde e paciente adulto",
      instruction_short: "Simula profissional de saúde e paciente adulto.",
      instruction_full: "Simula profissional de saúde e paciente adulto, com cuidado, tensão e consentimento claro.",
    },
    {
      label: "Dois desconhecidos em hotel",
      instruction_short: "Vocês são dois desconhecidos adultos em um hotel.",
      instruction_full: "Vocês são dois desconhecidos adultos em um hotel. A atração fica óbvia antes de alguém admitir.",
    },
    {
      label: "Policial e suspeita adulta",
      instruction_short: "Simula policial e suspeita adulta, sem medo real.",
      instruction_full: "Simula policial e suspeita adulta, sem violência real. A tensão fica no olhar, na ordem e na aproximação.",
    },
    {
      label: "Amantes escondidos",
      instruction_short: "Vocês são amantes fictícios se encontrando escondido.",
      instruction_full: "Vocês são amantes fictícios se encontrando escondido. A pressa e o segredo deixam tudo mais quente.",
    },
    {
      label: "Professor e aluno adulto",
      instruction_short: "Simula professor e aluno adulto.",
      instruction_full: "Simula professor e aluno adulto. A cena fica adulta, consensual e provocante, sem exagero teatral.",
    },
    {
      label: "Personal trainer e aluna adulta",
      instruction_short: "Simula personal trainer e aluna adulta.",
      instruction_full: "Simula personal trainer e aluna adulta. Usa comando, postura e proximidade pra aumentar a tensão.",
    },
    {
      label: "Personagem livre",
      instruction_short: "Escolhe um personagem adulto livre.",
      instruction_full: "Escolhe um personagem adulto livre e entra na cena com naturalidade, mantendo o foco no desejo entre vocês.",
    },
  ],
  "deriva-v1-card-042": [
    {
      label: "Sem pedir",
      instruction_short: "Na próxima carta, não pode pedir.",
      instruction_full: "Na próxima carta, não pode pedir. O desejo precisa aparecer no corpo, no olhar e na respiração.",
    },
    {
      label: "Sem usar as mãos",
      instruction_short: "Na próxima carta, não pode usar as mãos.",
      instruction_full: "Na próxima carta, não pode usar as mãos. Usa boca, corpo, voz e presença pra provocar.",
    },
    {
      label: "Sem beijo na boca",
      instruction_short: "Na próxima carta, não pode beijar na boca.",
      instruction_full: "Na próxima carta, não pode beijar na boca. Deixa a vontade crescer em volta do beijo proibido.",
    },
    {
      label: "Sem mudar de posição",
      instruction_short: "Na próxima carta, não pode mudar de posição.",
      instruction_full: "Na próxima carta, não pode mudar de posição. Varia ritmo, pressão e intenção sem trocar a base.",
    },
    {
      label: "Sem acelerar",
      instruction_short: "Na próxima carta, não pode acelerar.",
      instruction_full: "Na próxima carta, não pode acelerar. Sustenta o ritmo e deixa a tensão trabalhar por vocês.",
    },
  ],
};

async function main() {
  const defaultDeckKey = 'deriva-default-v1';
  
  let deck = await prisma.deck.findUnique({
    where: { system_key: defaultDeckKey }
  });

  if (!deck) {
    deck = await prisma.deck.create({
      data: {
        system_key: defaultDeckKey,
        name: 'Deck Padrão',
        type: 'SYSTEM',
        is_default: true,
      }
    });
  }

  // Ensure Unlock Group exists
  let darkGroup = await prisma.unlockGroup.findUnique({ where: { key: 'DARK_THIRD_IMAGINATION' } });
  if (!darkGroup) {
    darkGroup = await prisma.unlockGroup.create({
      data: {
        key: 'DARK_THIRD_IMAGINATION',
        title: 'Tons mais escuros',
        description: 'Fantasias com terceiros invisíveis, ciúme consentido e papéis avançados.',
        is_active: true,
      }
    });
  }

  // Ensure Dark Deck exists
  let darkDeck = await prisma.deck.findUnique({ where: { system_key: 'deriva-dark-v1' } });
  if (!darkDeck) {
    darkDeck = await prisma.deck.create({
      data: {
        system_key: 'deriva-dark-v1',
        name: 'Tons mais escuros',
        description: 'Um deck focado exclusivamente em ciúme consentido, imaginação com terceiros e papéis intensos.',
        type: 'OFFICIAL',
        is_default: false,
        requires_couple_unlock: true,
        unlock_group_key: 'DARK_THIRD_IMAGINATION',
      }
    });
  }

  // Clear old cards to make room for the new set of 50 cards
  console.log("Deletando cartas antigas...");
  await prisma.card.deleteMany({});

  for (const card of cards) {
    const isDark = card.category === "PRETO";
    await prisma.card.upsert({
      where: { system_key: card.system_key },
      update: {
        deck_id: isDark ? darkDeck.id : deck.id,
        title: card.title,
        body: card.body,
        category: card.category as CardCategory,
        intensity: card.intensity as CardIntensity,
        position: card.position,
        is_invertible: card.is_invertible,
        requires_video: card.requires_video,
        receiver_rule: card.receiver_rule as ReceiverRule,
        session_short_text: (card as Record<string, unknown>).session_short_text as string | null,
        primary_tag: (card as Record<string, unknown>).primary_tag as CardTag | null,
        stage: (card as Record<string, unknown>).stage as SessionStage | null,
        erotic_function: (card as Record<string, unknown>).erotic_function as EroticFunction | null,
        progression_role: (card as Record<string, unknown>).progression_role as ProgressionRole | null,
        requires_couple_unlock: isDark,
        random_options_enabled: Boolean((card as Record<string, unknown>).random_options_enabled),
        persist_random_option: Boolean((card as Record<string, unknown>).persist_random_option ?? true),
        unlock_group_key: isDark ? "DARK_THIRD_IMAGINATION" : null,
        is_available_in_default: !isDark,
        is_available_in_estreia: !isDark,
        is_available_in_custom_selection: !isDark,
      },
      create: {
        deck_id: isDark ? darkDeck.id : deck.id,
        system_key: card.system_key,
        title: card.title,
        body: card.body,
        category: card.category as CardCategory,
        intensity: card.intensity as CardIntensity,
        position: card.position,
        is_invertible: card.is_invertible,
        requires_video: card.requires_video,
        receiver_rule: card.receiver_rule as ReceiverRule,
        session_short_text: (card as Record<string, unknown>).session_short_text as string | null,
        primary_tag: (card as Record<string, unknown>).primary_tag as CardTag | null,
        stage: (card as Record<string, unknown>).stage as SessionStage | null,
        erotic_function: (card as Record<string, unknown>).erotic_function as EroticFunction | null,
        progression_role: (card as Record<string, unknown>).progression_role as ProgressionRole | null,
        requires_couple_unlock: isDark,
        random_options_enabled: Boolean((card as Record<string, unknown>).random_options_enabled),
        persist_random_option: Boolean((card as Record<string, unknown>).persist_random_option ?? true),
        unlock_group_key: isDark ? "DARK_THIRD_IMAGINATION" : null,
        is_available_in_default: !isDark,
        is_available_in_estreia: !isDark,
        is_available_in_custom_selection: !isDark,
      }
    });
  }

  for (const [systemKey, options] of Object.entries(randomOptionsBySystemKey)) {
    const optionCard = await prisma.card.findUnique({
      where: { system_key: systemKey },
      select: { id: true },
    });
    if (!optionCard) continue;

    await prisma.cardRandomOption.deleteMany({ where: { card_id: optionCard.id } });

    for (const [index, option] of options.entries()) {
      await prisma.cardRandomOption.create({
        data: {
          id: `${systemKey}-option-${String(index + 1).padStart(2, "0")}`,
          card_id: optionCard.id,
          label: option.label,
          instruction_short: option.instruction_short,
          instruction_full: option.instruction_full,
          weight: option.weight ?? 1,
          is_active: true,
        },
      });
    }
  }


  
  console.log('Seed completed successfully.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
