import { PrismaClient, CardCategory, CardIntensity, CardTag, EroticFunction, ProgressionRole, ReceiverRule, SessionStage } from '@prisma/client';
import { Pool } from 'pg';
import { PrismaPg } from '@prisma/adapter-pg';
import { config } from 'dotenv';

config();

let connectionString = process.env.DATABASE_URL || '';

if (connectionString.startsWith('prisma+postgres://localhost')) {
  connectionString = 'postgres://postgres:postgres@localhost:51214/template1?sslmode=disable';
}

const pool = new Pool({ connectionString });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });
const cards = [
  {
    "position": 1,
    "system_key": "deriva-v1-card-001",
    "title": "Escolha do corpo",
    "category": "AZUL",
    "intensity": "LEVE",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "TOQUE_LEVE",
    "stage": "OPENING",
    "erotic_function": "PREPARO",
    "progression_role": "ABRIR",
    "body": "Começa com uma massagem livre e gostosa no corpo inteiro. Ela só relaxa e guia o ritmo com pouca palavra ou gemido.",
    "session_short_text": "Faz uma massagem gostosa no corpo inteiro. Ela relaxa e curte.",
    "random_options_enabled": true,
    "persist_random_option": true
  },
  {
    "position": 2,
    "system_key": "deriva-v1-card-002",
    "title": "Mãos lentas",
    "category": "AZUL",
    "intensity": "LEVE",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "TOQUE_LEVE",
    "stage": "OPENING",
    "erotic_function": "PREPARO",
    "progression_role": "ABRIR",
    "body": "Toca o corpo inteiro dela bem devagar, sem pressa e sem ir direto pras partes íntimas. Acorda cada pedacinho da pele antes de aumentar a intensidade.",
    "session_short_text": "Toca o corpo inteiro dela bem devagar, sem pressa nenhuma. Acorda a pele toda.",
    "random_options_enabled": false,
    "persist_random_option": true
  },
  {
    "position": 3,
    "system_key": "deriva-v1-card-003",
    "title": "Mapa de calor",
    "category": "AZUL",
    "intensity": "QUENTE",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "TOQUE_INTIMO",
    "stage": "WARMUP",
    "erotic_function": "PROVOCACAO",
    "progression_role": "AQUECER",
    "body": "Ela escolhe três partes do corpo. Alterna entre mãos, boca e respiração quente, explorando sem pressa cada uma delas.",
    "session_short_text": "Ela escolhe três partes do corpo. Explora elas com mãos, boca e respiração.",
    "random_options_enabled": false,
    "persist_random_option": true
  },
  {
    "position": 4,
    "system_key": "deriva-v1-card-004",
    "title": "Só pode provocar",
    "category": "AZUL",
    "intensity": "QUENTE",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "PROIBICAO",
    "stage": "TEASING",
    "erotic_function": "PROVOCACAO",
    "progression_role": "PROVOCAR",
    "body": "Beija, encosta e provoca bastante, mas não avança pro ato principal. Deixa o desejo crescer forte.",
    "session_short_text": "Beija, encosta e provoca bastante, mas não avança pro principal. Deixa a vontade subir.",
    "random_options_enabled": false,
    "persist_random_option": true
  },
  {
    "position": 5,
    "system_key": "deriva-v1-card-005",
    "title": "Profissional e cliente",
    "category": "AZUL",
    "intensity": "QUENTE",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "ROLEPLAY",
    "stage": "TEASING",
    "erotic_function": "PROVOCACAO",
    "progression_role": "PROVOCAR",
    "body": "Você é o profissional. Começa com uma massagem séria e técnica. Aos poucos deixa o toque ficar mais íntimo, quente e provocante.",
    "session_short_text": "Começa a massagem bem sério. Deixa o toque escorregar devagar pro íntimo.",
    "random_options_enabled": false,
    "persist_random_option": true
  },
  {
    "position": 6,
    "system_key": "deriva-v1-card-006",
    "title": "Sem pressa, sem fala",
    "category": "AZUL",
    "intensity": "LEVE",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "CONEXAO",
    "stage": "WARMUP",
    "erotic_function": "PREPARO",
    "progression_role": "AQUECER",
    "body": "Fica em silêncio. Só toca, respira, beija e olha. Percebe o corpo dela com calma e atenção.",
    "session_short_text": "Silêncio total. Só toque, respiração, beijo e olhar profundo.",
    "random_options_enabled": false,
    "persist_random_option": true
  },
  {
    "position": 7,
    "system_key": "deriva-v1-card-007",
    "title": "Bebida e olhar",
    "category": "DERIVA",
    "intensity": "LEVE",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "RESPIRO",
    "stage": "COOLDOWN",
    "erotic_function": "RESPIRO",
    "progression_role": "RESPIRAR",
    "body": "Toma um gole, chega bem perto e fica olhando nos olhos por uns segundos. Depois fala o que está com mais vontade agora.",
    "session_short_text": "Toma um gole, olha bem no fundo dos olhos e fala o que quer fazer.",
    "random_options_enabled": false,
    "persist_random_option": true
  },
  {
    "position": 8,
    "system_key": "deriva-v1-card-008",
    "title": "Beijo que desce",
    "category": "DERIVA",
    "intensity": "QUENTE",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "BEIJO",
    "stage": "WARMUP",
    "erotic_function": "PREPARO",
    "progression_role": "AQUECER",
    "body": "Começa beijando na boca e vai descendo bem devagar pelo pescoço, colo, barriga ou costas, sentindo cada reação.",
    "session_short_text": "Começa com beijo na boca e desce lentamente pelo corpo.",
    "random_options_enabled": false,
    "persist_random_option": true
  },
  {
    "position": 9,
    "system_key": "deriva-v1-card-009",
    "title": "Uma frase perigosa",
    "category": "DERIVA",
    "intensity": "QUENTE",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "DIRTY_TALK",
    "stage": "TEASING",
    "erotic_function": "PROVOCACAO",
    "progression_role": "PROVOCAR",
    "body": "Fala baixinho no ouvido dela: “Agora eu quero...”. Seja direto e safado.",
    "session_short_text": "Fala bem baixinho no ouvido: “Agora eu quero...”.",
    "random_options_enabled": false,
    "persist_random_option": true
  },
  {
    "position": 10,
    "system_key": "deriva-v1-card-010",
    "title": "Controle suspenso",
    "category": "DERIVA",
    "intensity": "QUENTE",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "PROIBICAO",
    "stage": "TEASING",
    "erotic_function": "PROVOCACAO",
    "progression_role": "PROVOCAR",
    "body": "Escolhe uma regra pra próxima carta e sussurra pra ela: sem mãos, sem beijo na boca, sem tirar a roupa que sobrou ou sem tocar nas partes íntimas ainda.",
    "session_short_text": "Escolhe uma regra provocante pra próxima carta.",
    "random_options_enabled": false,
    "persist_random_option": true
  },
  {
    "position": 11,
    "system_key": "deriva-v1-card-011",
    "title": "Pausa grudada",
    "category": "DERIVA",
    "intensity": "LEVE",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "RESPIRO",
    "stage": "COOLDOWN",
    "erotic_function": "RESPIRO",
    "progression_role": "RESPIRAR",
    "body": "Fica bem coladinho, corpo com corpo, sem pressa pra avançar. Guia a mão dela pra onde quiser ser tocada.",
    "session_short_text": "Fica bem grudado, curtindo o corpo encostado sem pressa.",
    "random_options_enabled": false,
    "persist_random_option": true
  },
  {
    "position": 12,
    "system_key": "deriva-v1-card-012",
    "title": "Provocação merecida",
    "category": "DERIVA",
    "intensity": "QUENTE",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "PROVOCACAO",
    "stage": "TEASING",
    "erotic_function": "PROVOCACAO",
    "progression_role": "PROVOCAR",
    "body": "Quando alguém pula uma carta, entra uma provocação leve. Se ninguém pulou, a provocação vem só pelo prazer de brincar.",
    "session_short_text": "Uma provocação leve entra na cena.",
    "random_options_enabled": true,
    "persist_random_option": true
  },
  {
    "position": 13,
    "system_key": "deriva-v1-card-013",
    "title": "Ela guia",
    "category": "ROSA",
    "intensity": "INTENSO",
    "is_invertible": true,
    "requires_video": false,
    "receiver_rule": "WOMAN",
    "primary_tag": "COMANDO_DELA",
    "stage": "BUILDUP",
    "erotic_function": "PRAZER_NELA",
    "progression_role": "INTENSIFICAR",
    "body": "Dá pra ela o prazer com boca e mãos. Ela guia o ritmo, a pressão e a posição como quiser, sem explicar nada.",
    "session_short_text": "Dá prazer nela com boca e mãos. Ela guia tudo do jeito que gosta.",
    "random_options_enabled": false,
    "persist_random_option": true
  },
  {
    "position": 14,
    "system_key": "deriva-v1-card-014",
    "title": "Controle dela",
    "category": "ROSA",
    "intensity": "INTENSO",
    "is_invertible": true,
    "requires_video": false,
    "receiver_rule": "WOMAN",
    "primary_tag": "CONTROLE_DELA",
    "stage": "BUILDUP",
    "erotic_function": "PRAZER_NELA",
    "progression_role": "INTENSIFICAR",
    "body": "Ela escolhe a posição que quer receber prazer e marca o ritmo. Você só obedece e acompanha.",
    "session_short_text": "Ela escolhe a posição e controla o ritmo inteiro.",
    "random_options_enabled": false,
    "persist_random_option": true
  },
  {
    "position": 15,
    "system_key": "deriva-v1-card-015",
    "title": "Boca e pausa",
    "category": "ROSA",
    "intensity": "INTENSO",
    "is_invertible": true,
    "requires_video": false,
    "receiver_rule": "WOMAN",
    "primary_tag": "ORAL_NELA",
    "stage": "BUILDUP",
    "erotic_function": "PRAZER_NELA",
    "progression_role": "INTENSIFICAR",
    "body": "Alterna entre chupar bem gostoso e fazer pausas provocantes. Deixa ela louca de vontade entre uma e outra.",
    "session_short_text": "Alterna boca intensa com pausas bem safadas.",
    "random_options_enabled": false,
    "persist_random_option": true
  },
  {
    "position": 16,
    "system_key": "deriva-v1-card-016",
    "title": "Ela por cima",
    "category": "ROSA",
    "intensity": "INTENSO",
    "is_invertible": true,
    "requires_video": false,
    "receiver_rule": "WOMAN",
    "primary_tag": "CONTROLE_DELA",
    "stage": "INTENSE",
    "erotic_function": "PRAZER_CASAL",
    "progression_role": "SUSTENTAR",
    "body": "Ela fica por cima e assume o controle total. Ritmo, profundidade, velocidade — tudo no tempo dela.",
    "session_short_text": "Ela fica por cima e domina o ritmo.",
    "random_options_enabled": false,
    "persist_random_option": true
  },
  {
    "position": 17,
    "system_key": "deriva-v1-card-017",
    "title": "Só o clímax importa",
    "category": "ROSA",
    "intensity": "INTENSO",
    "is_invertible": true,
    "requires_video": false,
    "receiver_rule": "WOMAN",
    "primary_tag": "FOCO_NELA",
    "stage": "INTENSE",
    "erotic_function": "PRAZER_NELA",
    "progression_role": "SUSTENTAR",
    "body": "O foco é só o prazer dela. Dedica todo o tempo pra deixar ela cada vez mais excitada e entregue, sem cobrança de orgasmo.",
    "session_short_text": "Tudo pelo prazer dela. Entrega total.",
    "random_options_enabled": false,
    "persist_random_option": true
  },
  {
    "position": 18,
    "system_key": "deriva-v1-card-018",
    "title": "Guia sem vergonha",
    "category": "ROSA",
    "intensity": "INTENSO",
    "is_invertible": true,
    "requires_video": false,
    "receiver_rule": "WOMAN",
    "primary_tag": "COMANDO_DELA",
    "stage": "TEASING",
    "erotic_function": "PROVOCACAO",
    "progression_role": "PROVOCAR",
    "body": "Ela guia você com comandos curtos: “mais devagar”, “continua”, “mais forte”, “aí”, “não muda”. Obedece na hora.",
    "session_short_text": "Ela comanda com frases curtas e você obedece imediatamente.",
    "random_options_enabled": false,
    "persist_random_option": true
  },
  {
    "position": 19,
    "system_key": "deriva-v1-card-019",
    "title": "Mãos obedientes",
    "category": "ROSA",
    "intensity": "QUENTE",
    "is_invertible": true,
    "requires_video": false,
    "receiver_rule": "WOMAN",
    "primary_tag": "DOMINANCIA_LEVE",
    "stage": "TEASING",
    "erotic_function": "PROVOCACAO",
    "progression_role": "PROVOCAR",
    "body": "Ela posiciona suas mãos exatamente onde quer e você só move quando ela mandar.",
    "session_short_text": "Ela coloca suas mãos onde deseja e você obedece.",
    "random_options_enabled": false,
    "persist_random_option": true
  },
  {
    "position": 20,
    "system_key": "deriva-v1-card-020",
    "title": "Ela escolhe a sequência",
    "category": "ROSA",
    "intensity": "INTENSO",
    "is_invertible": true,
    "requires_video": false,
    "receiver_rule": "WOMAN",
    "primary_tag": "CONTROLE_DELA",
    "stage": "BUILDUP",
    "erotic_function": "PRAZER_NELA",
    "progression_role": "INTENSIFICAR",
    "body": "Ela decide a ordem: começa pela boca, depois mãos, oral ou posição de controle. Ela manda quando quer avançar ou trocar.",
    "session_short_text": "Ela decide a sequência e dita o ritmo de tudo.",
    "random_options_enabled": false,
    "persist_random_option": true
  },
  {
    "position": 21,
    "system_key": "deriva-v1-card-021",
    "title": "Vontade confessada",
    "category": "ROSA",
    "intensity": "QUENTE",
    "is_invertible": true,
    "requires_video": false,
    "receiver_rule": "WOMAN",
    "primary_tag": "DIRTY_TALK",
    "stage": "TEASING",
    "erotic_function": "PROVOCACAO",
    "progression_role": "PROVOCAR",
    "body": "Ela completa: “Hoje eu quero que você...”. Realiza exatamente o que ela pedir.",
    "session_short_text": "Ela fala o que quer e você realiza.",
    "random_options_enabled": false,
    "persist_random_option": true
  },
  {
    "position": 22,
    "system_key": "deriva-v1-card-022",
    "title": "Tela para ela",
    "category": "ROXO",
    "intensity": "INTENSO",
    "is_invertible": true,
    "requires_video": true,
    "receiver_rule": "WOMAN",
    "primary_tag": "VIDEO",
    "stage": "INTENSE",
    "erotic_function": "VIDEO_ESTIMULO",
    "progression_role": "SUSTENTAR",
    "body": "Sorteia um vídeo picante pra ela. Ela assiste enquanto recebe prazer do jeito que mais gosta.",
    "session_short_text": "Sorteia um vídeo focado nela enquanto você dá prazer.",
    "random_options_enabled": false,
    "persist_random_option": true
  },
  {
    "position": 23,
    "system_key": "deriva-v1-card-023",
    "title": "Tela para ele",
    "category": "ROXO",
    "intensity": "INTENSO",
    "is_invertible": true,
    "requires_video": true,
    "receiver_rule": "MAN",
    "primary_tag": "VIDEO",
    "stage": "INTENSE",
    "erotic_function": "VIDEO_ESTIMULO",
    "progression_role": "SUSTENTAR",
    "body": "Sorteia um vídeo mais forte pro gosto dele. Ele assiste enquanto recebe atenção intensa.",
    "session_short_text": "Sorteia um vídeo forte enquanto você cuida dele.",
    "random_options_enabled": false,
    "persist_random_option": true
  },
  {
    "position": 24,
    "system_key": "deriva-v1-card-024",
    "title": "Sem tela, só boca",
    "category": "ROXO",
    "intensity": "INTENSO",
    "is_invertible": true,
    "requires_video": false,
    "receiver_rule": "ANY",
    "primary_tag": "FOCO_NELA",
    "stage": "BUILDUP",
    "erotic_function": "PRAZER_NELA",
    "progression_role": "INTENSIFICAR",
    "body": "Sem vídeo. Relaxa e guia enquanto recebe boca e mãos alternando intensidade.",
    "session_short_text": "Sem tela. Só boca e mãos variando as sensações.",
    "random_options_enabled": false,
    "persist_random_option": true
  },
  {
    "position": 25,
    "system_key": "deriva-v1-card-025",
    "title": "Três vídeos, uma escolha",
    "category": "ROXO",
    "intensity": "INTENSO",
    "is_invertible": true,
    "requires_video": true,
    "receiver_rule": "ANY",
    "primary_tag": "VIDEO",
    "stage": "INTENSE",
    "erotic_function": "VIDEO_ESTIMULO",
    "progression_role": "SUSTENTAR",
    "body": "Sorteia vídeos até encontrar um que agrade. Ela assiste relaxando enquanto você executa com mãos, boca ou vibrador.",
    "session_short_text": "Sorteia um vídeo e executa enquanto ela assiste.",
    "random_options_enabled": false,
    "persist_random_option": true
  },
  {
    "position": 26,
    "system_key": "deriva-v1-card-026",
    "title": "Copiar só a energia",
    "category": "ROXO",
    "intensity": "INTENSO",
    "is_invertible": true,
    "requires_video": true,
    "receiver_rule": "ANY",
    "primary_tag": "COPIAR_ENERGIA",
    "stage": "INTENSE",
    "erotic_function": "PRAZER_CASAL",
    "progression_role": "SUSTENTAR",
    "body": "Sorteia um vídeo curto. Não copia tudo, mas traz a mesma energia, ritmo e atitude da cena.",
    "session_short_text": "Sorteia um vídeo e copia a energia dele.",
    "random_options_enabled": false,
    "persist_random_option": true
  },
  {
    "position": 27,
    "system_key": "deriva-v1-card-027",
    "title": "Oral interrompido",
    "category": "ROXO",
    "intensity": "INTENSO",
    "is_invertible": true,
    "requires_video": false,
    "receiver_rule": "ANY",
    "primary_tag": "PROVOCACAO",
    "stage": "INTENSE",
    "erotic_function": "PROVOCACAO",
    "progression_role": "SUSTENTAR",
    "body": "Chupa e estimula até ela quase gozar, então para de forma safada, beija, olha e provoca antes de voltar.",
    "session_short_text": "Leva ela quase no limite e interrompe de forma bem provocante.",
    "random_options_enabled": false,
    "persist_random_option": true
  },
  {
    "position": 28,
    "system_key": "deriva-v1-card-028",
    "title": "O receptor manda",
    "category": "ROXO",
    "intensity": "INTENSO",
    "is_invertible": true,
    "requires_video": false,
    "receiver_rule": "ANY",
    "primary_tag": "COMANDO_DELA",
    "stage": "BUILDUP",
    "erotic_function": "PRAZER_NELA",
    "progression_role": "INTENSIFICAR",
    "body": "Ela escolhe: oral, mãos, vibrador ou combinação. Você executa exatamente como ela quer.",
    "session_short_text": "Ela escolhe a técnica e você obedece com vontade.",
    "random_options_enabled": false,
    "persist_random_option": true
  },
  {
    "position": 29,
    "system_key": "deriva-v1-card-029",
    "title": "Ritmo crescente",
    "category": "VERMELHO",
    "intensity": "INTENSO",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "PENETRACAO",
    "stage": "INTENSE",
    "erotic_function": "PRAZER_CASAL",
    "progression_role": "INTENSIFICAR",
    "body": "Começa bem lento e vai aumentando a intensidade aos poucos até ficar animal.",
    "session_short_text": "Começa devagar e vai acelerando até virar fogo.",
    "random_options_enabled": false,
    "persist_random_option": true
  },
  {
    "position": 30,
    "system_key": "deriva-v1-card-030",
    "title": "Posição escolhida por ela",
    "category": "VERMELHO",
    "intensity": "INTENSO",
    "is_invertible": true,
    "requires_video": false,
    "receiver_rule": "WOMAN",
    "primary_tag": "CONTROLE_DELA",
    "stage": "INTENSE",
    "erotic_function": "PRAZER_CASAL",
    "progression_role": "SUSTENTAR",
    "body": "Ela escolhe a posição e o ritmo inicial. Você acompanha e só toma mais controle se ela permitir.",
    "session_short_text": "Ela define a posição e o ritmo.",
    "random_options_enabled": false,
    "persist_random_option": true
  },
  {
    "position": 31,
    "system_key": "deriva-v1-card-031",
    "title": "Forte, mas atento",
    "category": "VERMELHO",
    "intensity": "PICO",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "PENETRACAO",
    "stage": "PEAK",
    "erotic_function": "PICO",
    "progression_role": "PICO",
    "body": "Pode ser forte e fundo, mas fica sempre atento à respiração e às reações dela.",
    "session_short_text": "Intensidade alta, mas sempre ligado nos sinais dela.",
    "random_options_enabled": false,
    "persist_random_option": true
  },
  {
    "position": 32,
    "system_key": "deriva-v1-card-032",
    "title": "Sem trocar por 3 minutos",
    "category": "VERMELHO",
    "intensity": "INTENSO",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "PENETRACAO",
    "stage": "INTENSE",
    "erotic_function": "PRAZER_CASAL",
    "progression_role": "SUSTENTAR",
    "body": "Escolhe uma posição e fica nela. Varia o ritmo, a profundidade, o beijo e a pressão sem trocar de posição.",
    "session_short_text": "Fica na mesma posição e varia intensidade e movimento.",
    "random_options_enabled": false,
    "persist_random_option": true
  },
  {
    "position": 33,
    "system_key": "deriva-v1-card-033",
    "title": "Ela no comando do fim",
    "category": "VERMELHO",
    "intensity": "PICO",
    "is_invertible": true,
    "requires_video": false,
    "receiver_rule": "WOMAN",
    "primary_tag": "FECHAMENTO",
    "stage": "PEAK",
    "erotic_function": "PICO",
    "progression_role": "FECHAR",
    "body": "Ela decide como termina esta carta: mais lenta, mais forte, com pausa provocante, trocando de posição ou encerrando suave.",
    "session_short_text": "Ela decide como termina a carta.",
    "random_options_enabled": false,
    "persist_random_option": true
  },
  {
    "position": 34,
    "system_key": "deriva-v1-card-034",
    "title": "Proibido penetrar",
    "category": "VERMELHO",
    "intensity": "INTENSO",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "SEM_PENETRACAO",
    "stage": "INTENSE",
    "erotic_function": "PROVOCACAO",
    "progression_role": "SUSTENTAR",
    "body": "Nada de penetração agora. Explora só com boca, mãos, corpo, beijo e esfregação pra deixar a vontade explodir.",
    "session_short_text": "Proibido penetrar. Vale tudo o resto pra provocar.",
    "random_options_enabled": false,
    "persist_random_option": true
  },
  {
    "position": 35,
    "system_key": "deriva-v1-card-035",
    "title": "Pico opcional",
    "category": "VERMELHO",
    "intensity": "PICO",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "PICO",
    "stage": "PEAK",
    "erotic_function": "PICO",
    "progression_role": "PICO",
    "body": "Se ambos estiverem com muita vontade, sobe a intensidade pra algo mais forte e selvagem.",
    "session_short_text": "Se os dois quiserem, faz bem forte e selvagem.",
    "random_options_enabled": false,
    "persist_random_option": true
  },
  {
    "position": 36,
    "system_key": "deriva-v1-card-036",
    "title": "Personagens sorteados",
    "category": "PRETO",
    "intensity": "INTENSO",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "ROLEPLAY",
    "stage": "INTENSE",
    "erotic_function": "FANTASIA",
    "progression_role": "SUSTENTAR",
    "body": "Entra no personagem sorteado e vive a cena com ela intensamente.",
    "session_short_text": "Entra no fetiche sorteado sem hesitar.",
    "random_options_enabled": true,
    "persist_random_option": true
  },
  {
    "position": 37,
    "system_key": "deriva-v1-card-037",
    "title": "Mistério permitido",
    "category": "PRETO",
    "intensity": "PICO",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "IMAGINACAO",
    "stage": "PEAK",
    "erotic_function": "FANTASIA",
    "progression_role": "PICO",
    "body": "Fecha os olhos e mergulha na sua fantasia mais safada. Ela acompanha a energia sem perguntar nada.",
    "session_short_text": "Mergulha na sua fantasia secreta enquanto ela acompanha.",
    "random_options_enabled": false,
    "persist_random_option": true
  },
  {
    "position": 38,
    "system_key": "deriva-v1-card-038",
    "title": "Ordem sussurrada",
    "category": "PRETO",
    "intensity": "INTENSO",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "DOMINANCIA_LEVE",
    "stage": "INTENSE",
    "erotic_function": "PROVOCACAO",
    "progression_role": "INTENSIFICAR",
    "body": "Sussurra bem baixinho uma ordem safada no ouvido dela. Ela obedece.",
    "session_short_text": "Sussurra sua vontade bem safada e ela cumpre.",
    "random_options_enabled": false,
    "persist_random_option": true
  },
  {
    "position": 39,
    "system_key": "deriva-v1-card-039",
    "title": "Cena de hotel",
    "category": "PRETO",
    "intensity": "INTENSO",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "ROLEPLAY",
    "stage": "INTENSE",
    "erotic_function": "FANTASIA",
    "progression_role": "SUSTENTAR",
    "body": "Vocês são dois estranhos dividindo o mesmo quarto de hotel. A tensão sexual está no ar. Deixa a vontade falar mais alto.",
    "session_short_text": "Vocês são dois estranhos num hotel que se desejam muito.",
    "random_options_enabled": false,
    "persist_random_option": true
  },
  {
    "position": 40,
    "system_key": "deriva-v1-card-040",
    "title": "Profissional com deslize",
    "category": "PRETO",
    "intensity": "INTENSO",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "ROLEPLAY",
    "stage": "INTENSE",
    "erotic_function": "FANTASIA",
    "progression_role": "SUSTENTAR",
    "body": "Você é o profissional. Começa formal e vai deixando o toque cada vez mais safado e fora dos limites.",
    "session_short_text": "Começa como profissional e vai deslizando pro proibido.",
    "random_options_enabled": false,
    "persist_random_option": true
  },
  {
    "position": 41,
    "system_key": "deriva-v1-card-041",
    "title": "Terceira presença imaginária",
    "category": "PRETO",
    "intensity": "PICO",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "TERCEIRO_IMAGINARIO",
    "stage": "PEAK",
    "erotic_function": "FANTASIA",
    "progression_role": "PICO",
    "body": "Imagina que tem mais alguém assistindo vocês com desejo. Sente o tesão de estar sendo observado.",
    "session_short_text": "Imagina que tem alguém olhando vocês com muita vontade.",
    "random_options_enabled": false,
    "persist_random_option": true
  },
  {
    "position": 42,
    "system_key": "deriva-v1-card-042",
    "title": "Proibição mental",
    "category": "PRETO",
    "intensity": "INTENSO",
    "is_invertible": false,
    "requires_video": false,
    "receiver_rule": "NONE",
    "primary_tag": "PROIBICAO",
    "stage": "INTENSE",
    "erotic_function": "PROVOCACAO",
    "progression_role": "SUSTENTAR",
    "body": "Escolhe uma regra e obedece na próxima carta: sem pedir, sem usar as mãos, sem beijo na boca, sem mudar de posição ou sem acelerar.",
    "session_short_text": "Obedece uma regra proibitiva na próxima carta.",
    "random_options_enabled": true,
    "persist_random_option": true
  }
];

const randomOptionsBySystemKey: Record<string, Array<{ label: string; instruction_short: string; instruction_full: string; weight?: number }>> = {
  "deriva-v1-card-001": [
    {
      label: "Massagem livre",
      instruction_short: "Faz uma massagem gostosa no corpo inteiro. Ela relaxa e curte.",
      instruction_full: "Faz uma massagem gostosa no corpo inteiro. Ela relaxa e guia o ritmo com pouco som e pouca palavra.",
    },
    {
      label: "Profissional e cliente",
      instruction_short: "Começa como profissional e cliente.",
      instruction_full: "Entra na cena de profissional e cliente. Começa técnico, sério e atento, deixando o toque ficar íntimo aos poucos.",
    },
    {
      label: "Deslize provocante",
      instruction_short: "Deixa a massagem profissional escorregar pro íntimo.",
      instruction_full: "Começa como massagem profissional e deixa pequenos deslizes provocantes aparecerem devagar, sempre percebendo a reação dela.",
    },
  ],
  "deriva-v1-card-012": [
    {
      label: "Beijo demorado",
      instruction_short: "Dá um beijo demorado e cheio de intenção.",
      instruction_full: "Dá um beijo demorado, aproxima o corpo e deixa a provocação crescer sem pressa.",
    },
    {
      label: "Toque por cima da roupa",
      instruction_short: "Provoca por cima da roupa.",
      instruction_full: "Toca por cima da roupa com calma, pressão e malícia, sem entregar tudo de uma vez.",
    },
    {
      label: "Frase safada no ouvido",
      instruction_short: "Sussurra uma frase safada no ouvido.",
      instruction_full: "Chega no ouvido e solta uma frase safada, curta e direta, do jeito que deixa o clima mais perigoso.",
    },
    {
      label: "Sem tocar",
      instruction_short: "Fica sem tocar por um instante e só olha.",
      instruction_full: "Fica sem tocar por um instante. Só olha, respira perto e deixa a vontade incomodar gostoso.",
    },
  ],
  "deriva-v1-card-036": [
    {
      label: "Massagista e cliente",
      instruction_short: "Entra na cena de massagista e cliente.",
      instruction_full: "Entra na cena de massagista e cliente. Começa formal e deixa o desejo aparecer no toque.",
    },
    {
      label: "Profissional de saúde e paciente adulto",
      instruction_short: "Simula profissional de saúde e paciente adulto.",
      instruction_full: "Simula profissional de saúde e paciente adulto, com cuidado, tensão e consentimento claro.",
    },
    {
      label: "Dois desconhecidos em hotel",
      instruction_short: "Vocês são dois desconhecidos adultos em um hotel.",
      instruction_full: "Vocês são dois desconhecidos adultos em um hotel. A atração fica óbvia antes de alguém admitir.",
    },
    {
      label: "Policial e suspeita adulta",
      instruction_short: "Simula policial e suspeita adulta, sem medo real.",
      instruction_full: "Simula policial e suspeita adulta, sem violência real. A tensão fica no olhar, na ordem e na aproximação.",
    },
    {
      label: "Amantes escondidos",
      instruction_short: "Vocês são amantes fictícios se encontrando escondido.",
      instruction_full: "Vocês são amantes fictícios se encontrando escondido. A pressa e o segredo deixam tudo mais quente.",
    },
    {
      label: "Professor e aluno adulto",
      instruction_short: "Simula professor e aluno adulto.",
      instruction_full: "Simula professor e aluno adulto. A cena fica adulta, consensual e provocante, sem exagero teatral.",
    },
    {
      label: "Personal trainer e aluna adulta",
      instruction_short: "Simula personal trainer e aluna adulta.",
      instruction_full: "Simula personal trainer e aluna adulta. Usa comando, postura e proximidade pra aumentar a tensão.",
    },
    {
      label: "Personagem livre",
      instruction_short: "Escolhe um personagem adulto livre.",
      instruction_full: "Escolhe um personagem adulto livre e entra na cena com naturalidade, mantendo o foco no desejo entre vocês.",
    },
  ],
  "deriva-v1-card-042": [
    {
      label: "Sem pedir",
      instruction_short: "Na próxima carta, não pode pedir.",
      instruction_full: "Na próxima carta, não pode pedir. O desejo precisa aparecer no corpo, no olhar e na respiração.",
    },
    {
      label: "Sem usar as mãos",
      instruction_short: "Na próxima carta, não pode usar as mãos.",
      instruction_full: "Na próxima carta, não pode usar as mãos. Usa boca, corpo, voz e presença pra provocar.",
    },
    {
      label: "Sem beijo na boca",
      instruction_short: "Na próxima carta, não pode beijar na boca.",
      instruction_full: "Na próxima carta, não pode beijar na boca. Deixa a vontade crescer em volta do beijo proibido.",
    },
    {
      label: "Sem mudar de posição",
      instruction_short: "Na próxima carta, não pode mudar de posição.",
      instruction_full: "Na próxima carta, não pode mudar de posição. Varia ritmo, pressão e intenção sem trocar a base.",
    },
    {
      label: "Sem acelerar",
      instruction_short: "Na próxima carta, não pode acelerar.",
      instruction_full: "Na próxima carta, não pode acelerar. Sustenta o ritmo e deixa a tensão trabalhar por vocês.",
    },
  ],
};

async function main() {
  const defaultDeckKey = 'deriva-default-v1';
  
  let deck = await prisma.deck.findUnique({
    where: { system_key: defaultDeckKey }
  });

  if (!deck) {
    deck = await prisma.deck.create({
      data: {
        system_key: defaultDeckKey,
        name: 'Deck Padrão',
        type: 'SYSTEM',
        is_default: true,
      }
    });
  }

  // Ensure Unlock Group exists
  let darkGroup = await prisma.unlockGroup.findUnique({ where: { key: 'DARK_THIRD_IMAGINATION' } });
  if (!darkGroup) {
    darkGroup = await prisma.unlockGroup.create({
      data: {
        key: 'DARK_THIRD_IMAGINATION',
        title: 'Tons mais escuros',
        description: 'Fantasias com terceiros invisíveis, ciúme consentido e papéis avançados.',
        is_active: true,
      }
    });
  }

  // Ensure Dark Deck exists
  let darkDeck = await prisma.deck.findUnique({ where: { system_key: 'deriva-dark-v1' } });
  if (!darkDeck) {
    darkDeck = await prisma.deck.create({
      data: {
        system_key: 'deriva-dark-v1',
        name: 'Tons mais escuros',
        description: 'Um deck focado exclusivamente em ciúme consentido, imaginação com terceiros e papéis intensos.',
        type: 'OFFICIAL',
        is_default: false,
        requires_couple_unlock: true,
        unlock_group_key: 'DARK_THIRD_IMAGINATION',
      }
    });
  }

  for (const card of cards) {
    const isDark = card.system_key === "deriva-v1-card-041";
    await prisma.card.upsert({
      where: { system_key: card.system_key },
      update: {
        deck_id: isDark ? darkDeck.id : deck.id,
        title: card.title,
        body: card.body,
        category: card.category as CardCategory,
        intensity: card.intensity as CardIntensity,
        position: card.position,
        is_invertible: card.is_invertible,
        requires_video: card.requires_video,
        receiver_rule: card.receiver_rule as ReceiverRule,
        session_short_text: (card as Record<string, unknown>).session_short_text as string | null,
        primary_tag: (card as Record<string, unknown>).primary_tag as CardTag | null,
        stage: (card as Record<string, unknown>).stage as SessionStage | null,
        erotic_function: (card as Record<string, unknown>).erotic_function as EroticFunction | null,
        progression_role: (card as Record<string, unknown>).progression_role as ProgressionRole | null,
        requires_couple_unlock: isDark,
        random_options_enabled: Boolean((card as Record<string, unknown>).random_options_enabled),
        persist_random_option: Boolean((card as Record<string, unknown>).persist_random_option ?? true),
        unlock_group_key: isDark ? "DARK_THIRD_IMAGINATION" : null,
        is_available_in_default: !isDark,
        is_available_in_estreia: !isDark,
        is_available_in_custom_selection: !isDark,
      },
      create: {
        deck_id: isDark ? darkDeck.id : deck.id,
        system_key: card.system_key,
        title: card.title,
        body: card.body,
        category: card.category as CardCategory,
        intensity: card.intensity as CardIntensity,
        position: card.position,
        is_invertible: card.is_invertible,
        requires_video: card.requires_video,
        receiver_rule: card.receiver_rule as ReceiverRule,
        session_short_text: (card as Record<string, unknown>).session_short_text as string | null,
        primary_tag: (card as Record<string, unknown>).primary_tag as CardTag | null,
        stage: (card as Record<string, unknown>).stage as SessionStage | null,
        erotic_function: (card as Record<string, unknown>).erotic_function as EroticFunction | null,
        progression_role: (card as Record<string, unknown>).progression_role as ProgressionRole | null,
        requires_couple_unlock: isDark,
        random_options_enabled: Boolean((card as Record<string, unknown>).random_options_enabled),
        persist_random_option: Boolean((card as Record<string, unknown>).persist_random_option ?? true),
        unlock_group_key: isDark ? "DARK_THIRD_IMAGINATION" : null,
        is_available_in_default: !isDark,
        is_available_in_estreia: !isDark,
        is_available_in_custom_selection: !isDark,
      }
    });
  }

  for (const [systemKey, options] of Object.entries(randomOptionsBySystemKey)) {
    const optionCard = await prisma.card.findUnique({
      where: { system_key: systemKey },
      select: { id: true },
    });
    if (!optionCard) continue;

    await prisma.cardRandomOption.deleteMany({ where: { card_id: optionCard.id } });

    for (const [index, option] of options.entries()) {
      await prisma.cardRandomOption.create({
        data: {
          id: `${systemKey}-option-${String(index + 1).padStart(2, "0")}`,
          card_id: optionCard.id,
          label: option.label,
          instruction_short: option.instruction_short,
          instruction_full: option.instruction_full,
          weight: option.weight ?? 1,
          is_active: true,
        },
      });
    }
  }


  
  console.log('Seed completed successfully.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
